version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: root   # Defina o nome do usuário
      POSTGRES_PASSWORD: root  # Defina a senha
      POSTGRES_DB: precos  # Defina o nome do banco de dados
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # Mapeia a pasta atual para o volume do PostgreSQL
    ports:
      - "5432:5432"  # Mapeia a porta 5432 do contêiner para a porta 5432 do host
    restart: always
